language: python

python:
  - "2.6"
  - "2.7"
  - "3.4"

matrix:
  fast_finish: true
  allow_failures:
    - python: "3.4"

addons:
  apt:
    packages:
      # Packages we need to compile scipy for Python 2.6
      - libopenblas-base
      - libopenblas-dev
      - liblapack-dev
      - gfortran

# commands to be run before installation
before_install:
  - pip install --upgrade pip # Upgrade pip, so it can use wheels

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r pymc-requirements.txt
  - pip install -r multiprocess-requirements.txt
  - pip install -r test-requirements.txt

# command to run tests
script:
  - echo $TRAVIS_PYTHON_VERSION
  - if [ $TRAVIS_PYTHON_VERSION == '2.6' ]; then ./run_tests --noproc --verbose ; fi # Travis CI's Python2.6 environment is not able to deal with multiprocess for some reason
  - if [ $TRAVIS_PYTHON_VERSION != '2.6' ]; then ./run_tests --verbose ; fi

# command to run after tests
after_success:
  - coveralls
